"""Request-scoped observability context.

Provides ``ContextVar``-backed storage for the two per-request identifiers that
must flow through every log line regardless of which layer (middleware, service,
Celery task) emits the log:

- ``request_id``  — the value of the ``X-Request-Id`` header (preserved from
  the client or generated by ``RequestIdMiddleware``).
- ``user_id``     — the value of the ``X-User-Id`` header (opaque UUID string;
  may be absent for unauthenticated or internal callers).

Tenant context is NOT stored here — it already lives in
``apps.tenant.context`` and is read by ``RequestContextFilter`` at log time.

Usage
-----
``RequestIdMiddleware`` calls ``bind_request_context`` at the start of each
request and ``reset_request_context`` in a ``finally`` block::

    token = bind_request_context(request_id="abc", user_id="xyz")
    try:
        ...
    finally:
        reset_request_context(token)

Service-layer code that wants to read the current request id (e.g. to attach
it to an async task payload) calls ``get_request_id()`` / ``get_user_id()``.
The ``RequestContextFilter`` calls these implicitly on every ``LogRecord``.
"""

from __future__ import annotations

from contextvars import ContextVar
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from contextvars import Token

# ---------------------------------------------------------------------------
# ContextVars
# ---------------------------------------------------------------------------

_request_id_ctx: ContextVar[str | None] = ContextVar("request_id", default=None)
_user_id_ctx: ContextVar[str | None] = ContextVar("user_id", default=None)


# ---------------------------------------------------------------------------
# Public accessors
# ---------------------------------------------------------------------------


def get_request_id() -> str | None:
    """Return the active request id, or ``None`` if unset (e.g. in Celery tasks)."""
    return _request_id_ctx.get()


def get_user_id() -> str | None:
    """Return the active user id, or ``None`` if the header was absent."""
    return _user_id_ctx.get()


# ---------------------------------------------------------------------------
# Binding helpers used by RequestIdMiddleware
# ---------------------------------------------------------------------------


class _BoundContextToken:
    """Opaque token that carries the reset tokens for both ContextVars.

    Returned by ``bind_request_context``; passed to ``reset_request_context``.
    """

    __slots__ = ("_request_id_token", "_user_id_token")

    def __init__(
        self,
        request_id_token: "Token[str | None]",
        user_id_token: "Token[str | None]",
    ) -> None:
        self._request_id_token = request_id_token
        self._user_id_token = user_id_token


def bind_request_context(
    request_id: str | None,
    user_id: str | None,
) -> _BoundContextToken:
    """Set ``request_id`` and ``user_id`` in the current context.

    Returns a ``_BoundContextToken`` that must be passed to
    ``reset_request_context`` in a ``finally`` block to restore the
    previous context (important for ASGI where multiple coroutines share
    the same OS thread).

    Args:
        request_id: Value of the ``X-Request-Id`` header (or generated UUID).
        user_id:    Value of the ``X-User-Id`` header; ``None`` when absent.

    Returns:
        A token that can be used to restore the previous context.
    """
    rid_token = _request_id_ctx.set(request_id)
    uid_token = _user_id_ctx.set(user_id)
    return _BoundContextToken(rid_token, uid_token)


def reset_request_context(token: _BoundContextToken) -> None:
    """Restore the context to the state captured in ``token``.

    Must be called in a ``finally`` block after ``bind_request_context``.
    Silently ignores errors to avoid masking the original exception.
    """
    try:
        _request_id_ctx.reset(token._request_id_token)
        _user_id_ctx.reset(token._user_id_token)
    except Exception:  # noqa: BLE001
        pass
