"""Invoice PDF generation — ReportLab one-page receipt.

Writes a minimal PDF receipt to ``MEDIA_ROOT/invoices/<invoice_id>.pdf``
and returns the corresponding ``MEDIA_URL``-relative URL string.

ADR-NOTE: This is a local-filesystem stub.  Swap ``default_storage`` in
settings for S3/GCS in a later iteration; the contract (takes invoice data,
returns a URL string) does not change.

The generated PDF is intentionally simple: single page, black-on-white,
no images.  A richer template (logo, styling) can replace the canvas drawing
calls without changing the public function signature.
"""

from __future__ import annotations

from decimal import Decimal
from pathlib import Path
from uuid import UUID

from django.conf import settings


def render_invoice_pdf(
    *,
    invoice_id: UUID,
    order_id: UUID,
    invoice_number: int,
    tenant_name: str,
    total: Decimal,
    taxes: Decimal,
    currency: str,
) -> str:
    """Render a one-page invoice PDF and save it to MEDIA_ROOT.

    Args:
        invoice_id:     UUID of the ``Invoice`` row (used as the filename).
        order_id:       UUID of the parent ``Order`` (displayed on the PDF).
        invoice_number: Monotonic per-tenant invoice number.
        tenant_name:    Human-readable tenant name displayed as the merchant.
        total:          Order total (pre-tax snapshot).
        taxes:          Computed tax amount.
        currency:       ISO 4217 currency code.

    Returns:
        A URL string suitable for storing in ``Invoice.pdf_url``, e.g.
        ``/media/invoices/3f2504e0-...pdf``.

    Side effects:
        Creates ``MEDIA_ROOT/invoices/`` directory if it does not exist, then
        writes the PDF file.  Overwrites any existing file with the same name
        (safe because the invoice_id is a UUID4).
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm
    from reportlab.pdfgen import canvas as rl_canvas

    media_root = Path(settings.MEDIA_ROOT)
    invoice_dir = media_root / "invoices"
    invoice_dir.mkdir(parents=True, exist_ok=True)

    filename = f"{invoice_id}.pdf"
    file_path = invoice_dir / filename

    c = rl_canvas.Canvas(str(file_path), pagesize=A4)
    width, height = A4

    # --- Header ---
    c.setFont("Helvetica-Bold", 20)
    c.drawString(2 * cm, height - 3 * cm, f"INVOICE #{invoice_number}")

    c.setFont("Helvetica", 11)
    c.drawString(2 * cm, height - 4.2 * cm, f"Merchant: {tenant_name}")
    c.drawString(2 * cm, height - 5.0 * cm, f"Order: {order_id}")

    # --- Separator ---
    c.setLineWidth(0.5)
    c.line(2 * cm, height - 5.6 * cm, width - 2 * cm, height - 5.6 * cm)

    # --- Amounts table ---
    c.setFont("Helvetica", 12)
    row_y = height - 7 * cm

    c.drawString(2 * cm, row_y, "Subtotal (pre-tax)")
    c.drawRightString(width - 2 * cm, row_y, f"{total} {currency}")

    row_y -= 0.8 * cm
    c.drawString(2 * cm, row_y, "Taxes (15%)")
    c.drawRightString(width - 2 * cm, row_y, f"{taxes} {currency}")

    row_y -= 0.5 * cm
    c.line(2 * cm, row_y, width - 2 * cm, row_y)

    row_y -= 0.9 * cm
    grand_total = (total + taxes).quantize(Decimal("0.01"))
    c.setFont("Helvetica-Bold", 13)
    c.drawString(2 * cm, row_y, "Total due")
    c.drawRightString(width - 2 * cm, row_y, f"{grand_total} {currency}")

    # --- Footer ---
    c.setFont("Helvetica", 9)
    c.drawCentredString(
        width / 2,
        2 * cm,
        "Generated by cart_system — this is a system-generated document.",
    )

    c.save()

    media_url = getattr(settings, "MEDIA_URL", "/media/")
    return f"{media_url}invoices/{filename}"
